language: python
branches:
  only:
  - pelican
install:
- pip install -r requirements.txt
script:
- make travis
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: RRDobUdORG7imS+lgGSybHUI66kqF1d9Cbvlm4YjY6K/b/nmDyYNuW1a3STEPk6TKCRkcJuNiQvrbxAkwF2mQX7bfpQJP1wOiJfxJ1byxEPekQe97fwvyXXcROcAMMJxyTI52jqthju8g6OuzV7xJ4ZgOqE+5HaeyRfgp6qwr3mODtJWzG4oUOtyv1OkaUL8Ih0VXuE51xQQ76uALYr1xU7oXMINq/efscuro41eWFAsD9VdiQhcGM3FpKQGBdCgX66HA+oKT79+lf8BRrOUqK8YRaUmATUX9Mn1Myg5c15hudvhGjBzSh3AAC3afPCle4RotE0NTtdwfIYwhFACU5S7g+Fcje0riOts9ZX6/yXM4CB7DG6VQJyCd5XPVS0j5JszEFnCzETq7YJCSsbd+eQ87qzuK8vaAGqAfL/A4gYnbNhHCP5rABky+WfQfpwVJsZdfdZRsuHqQSbYx6RrQbEtwG4J9vLKJWBsaFCzpdUEXjWu4Ci5AJgjFzzsvwbualHkxsIE5Z3KcsJykt8kBcULW1sn1/vyU2reY3r8IaTdbbzR8ePfJIm80WE4MlQuUfjwWLE6yH+pZP6uAm6aAPwuejaRxSJIv13fKKu0G9vEUMyU2mfL3mDFzLTx1ffzu0A31etbAuge4O9gle+DodpeqFyIVVS7YWLjJJZoPEc=
